### PR TITLE
Add 'execute' and 'log' methods

### PR DESCRIPTION
**Pull request by alexandregv**
These methods can be used in the Cakefile, allowing user to execute shell commands and logging output/status with a nice format.

__log__:
```cr
log "Success!"
status = 1
log "Error!", status
```
A status of 0 (default) will print a success log, others status will print an error log.

__execute__:
```cr
execute "shards build"

# or with logs
execute(
  cmd: "shards build",
  announce: "Building binary...",
  success: "Binary built!",
  error: "Build failed."
)

# command's output can also be controlled with the 'output' parameter
execute(
  cmd: "crystal spec",
  announce: "Running specs...",
  success: "All specs passed successfully!",
  error: "Specs failed.",
  output: "error"
)
# like this, Specs output will only show if it returned errors
# ('output' can be "always", "never", "success" or "error")
```

**Here is a demo!**
[asciicast](https://asciinema.org/a/193756)

Here, I log all the commands and I print Spec's output only if it failed.
This allows a clean rendering, not ruined by the useless output of successful Specs.

**Make Tasks Great Again!**

### CODE REVIEW

**Comment by axvm** [comment]
Hi @triinoxys ! Thanks for PR in Cake! 👍 
I'm not sure if announce is a good choice to describe command. In my opinion the best way to describe whats going on is to use `desc` method before task implementation like

```ruby
desc "executing something"
task :exec_something do
  ret_code = execute('something')

  if ret_code == 0
    log "Success!"
  else
    fatal "Something went wrong. ret code is #{ret_code}"
  end
end
```

And the output must be something like this:
```
Running task: 'executing something'...
>(green) Success!
```
or if failed
```
Running task: 'executing something'...
>(red) Something went wrong. ret code is 1
```

I think it makes code more 'self-documented' than in your implementation. What do you think about it?

**Comment by alexandregv** [comment]
Hi @axvm !
Thanks for your answer 😃

Yeah, I spent a lot of time thinking about the way I go, I finally did like this because I found it easier to use.
I wanted to make usage easy and avoid the user having to type too much code and repeat code, such as the success/error handling part.

I think repeating stuff like
```ruby
if ret_code == 0
  log "Success!"
else
  fatal "Something went wrong. ret code is #{ret_code}"
end
```
in each task would be 'dirty' and boring.

More, if we use a pre-task desc like you said, it limits the desc to the whole task so if there are multiple `execute` in the same task, we have to puts the desc manually and handle error for each `execute`. I think this is very heavy.

Let me know what you think about it 😃

**Comment by axvm** [comment]
Hm... Now I understand the reason and agree w/ your opinion. 
May I ask you to cover your code w/ tests and to bump the minor version in `shard.yml`?

**Comment by axvm** [comment]
@triinoxys good job! Thank you for contributing in Cake

**Pull request merged**
